import { access, mkdir, mkdtemp, readFile, symlink, unlink, utimes, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { Project } from 'ts-morph'
import { describe, expect, it } from 'vitest'
import { ARTIFACT_MANIFEST_FILENAME, acquireOutputWriteLock, compareArtifacts, formatMaterializedArtifacts, hashArtifactContent, materializeArtifacts, sourceFileToArtifact, writeArtifacts } from './index.ts'

const generatedTypeScriptHeader = `/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

`
const decoder = new TextDecoder()
const encoder = new TextEncoder()

describe('generated artifacts', () => {
  it('materializes and compares multiple artifact kinds', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-artifacts-'))
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile('/virtual/example.ts', 'export const value=1')
    sourceFile.replaceWithText('export const value=1')
    const materialized = materializeArtifacts([
      { kind: 'text', path: 'readme.md', content: '# Generated\n' },
      { kind: 'json', path: 'data.json', value: { b: 2, a: 1 } },
      { kind: 'typescript', path: path.join(root, 'example.ts'), sourceFile },
      { kind: 'binary', path: 'asset.bin', content: new Uint8Array([0, 1, 2]) },
    ], root)
    expect(materialized.diagnostics).toEqual([])
    expect(new TextDecoder().decode(materialized.artifacts.find((artifact) => artifact.relativePath === 'data.json')?.content ?? new Uint8Array())).toBe('{\n  "a": 1,\n  "b": 2\n}\n')
    const manifest = await compareArtifacts(materialized.artifacts, root)
    expect(manifest.summary.added).toBe(4)
    await writeArtifacts(materialized.artifacts, manifest)
    await writeFile(path.join(root, 'stale.txt'), 'stale')
    const next = await compareArtifacts(materialized.artifacts, root, true)
    expect(next.summary).toMatchObject({ unchanged: 4, deleted: 0 })
    expect(await readFile(path.join(root, 'stale.txt'), 'utf8')).toBe('stale')
    expect(hashArtifactContent(materialized.artifacts[0]?.content ?? new Uint8Array())).toMatch(/^[a-f0-9]{64}$/)
    const ownership = JSON.parse(await readFile(path.join(root, ARTIFACT_MANIFEST_FILENAME), 'utf8'))
    expect(ownership.version).toBe(2)
    expect(ownership.files.map(({ path: managedPath }: { path: string }) => managedPath)).toEqual(['asset.bin', 'data.json', 'example.ts', 'readme.md'])
  })

  it('prepends the canonical header before TypeScript source and hashes the final bytes', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-generated-header-'))
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile(
      path.join(root, 'example.ts'),
      "import { dependency } from './dependency'\n\nconst marker = '@generated'\nexport { dependency, marker }\n",
    )
    const first = materializeArtifacts([{ kind: 'typescript', path: sourceFile.getFilePath(), sourceFile }], root)
    const second = materializeArtifacts([{ kind: 'typescript', path: sourceFile.getFilePath(), sourceFile }], root)
    const firstArtifact = first.artifacts[0]
    const secondArtifact = second.artifacts[0]
    const content = decoder.decode(firstArtifact?.content)

    expect(first.diagnostics).toEqual([])
    expect(content).toBe(
      `${generatedTypeScriptHeader}import { dependency } from './dependency';\n\nconst marker = '@generated';\nexport { dependency, marker };\n`,
    )
    expect(content.indexOf(generatedTypeScriptHeader)).toBe(0)
    expect(content.match(/Generated by openapi-to\. DO NOT EDIT\./g)).toHaveLength(1)
    const expectedBytes = encoder.encode(content)
    expect(firstArtifact?.hash).toBe(hashArtifactContent(expectedBytes))
    const manifest = await compareArtifacts(first.artifacts, root)
    expect(manifest.entries).toEqual([
      expect.objectContaining({ path: 'example.ts', status: 'added', hash: firstArtifact?.hash, bytes: expectedBytes.byteLength }),
    ])
    expect(secondArtifact?.content).toEqual(firstArtifact?.content)
    expect(secondArtifact?.hash).toBe(firstArtifact?.hash)
  })

  it('does not duplicate a complete canonical header at the start of TypeScript source', () => {
    const root = path.resolve('/tmp/existing-generated-header')
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile(
      path.join(root, 'example.ts'),
      `${generatedTypeScriptHeader}/** License notice. */\nexport const value = 1\n`,
    )
    const materialized = materializeArtifacts([sourceFileToArtifact(sourceFile)], root)
    const content = decoder.decode(materialized.artifacts[0]?.content)

    expect(materialized.diagnostics).toEqual([])
    expect(content.startsWith(`${generatedTypeScriptHeader}/** License notice. */`)).toBe(true)
    expect(content.match(/Generated by openapi-to\. DO NOT EDIT\./g)).toHaveLength(1)
  })

  it('applies the byte limit after adding the TypeScript header', () => {
    const root = path.resolve('/tmp/generated-header-size')
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile(path.join(root, 'empty.ts'), '')
    const materialized = materializeArtifacts([sourceFileToArtifact(sourceFile)], root, {
      maxArtifactBytes: encoder.encode(generatedTypeScriptHeader).byteLength - 1,
    })

    expect(materialized.artifacts).toEqual([])
    expect(materialized.diagnostics).toEqual([
      expect.objectContaining({ code: 'ARTIFACT_TOO_LARGE', location: { source: 'empty.ts' } }),
    ])
  })

  it('leaves text, JSON, and binary artifacts unchanged', () => {
    const root = path.resolve('/tmp/non-typescript-artifacts')
    const binary = new Uint8Array([0, 1, 2, 255])
    const materialized = materializeArtifacts([
      { kind: 'text', path: 'readme.md', content: '# @generated\n' },
      { kind: 'json', path: 'data.json', value: { generated: '@generated' } },
      { kind: 'binary', path: 'asset.bin', content: binary },
    ], root)

    expect(materialized.diagnostics).toEqual([])
    expect(decoder.decode(materialized.artifacts.find((artifact) => artifact.kind === 'text')?.content)).toBe('# @generated\n')
    const json = decoder.decode(materialized.artifacts.find((artifact) => artifact.kind === 'json')?.content)
    expect(json).toBe('{\n  "generated": "@generated"\n}\n')
    expect(JSON.parse(json)).toEqual({ generated: '@generated' })
    expect(materialized.artifacts.find((artifact) => artifact.kind === 'binary')?.content).toEqual(binary)
  })

  it('keeps exactly one TypeScript header through Biome formatting', async () => {
    const root = path.resolve('/tmp/biome-generated-header')
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile(
      path.join(root, 'example.ts'),
      'export const value={answer:42}\n',
    )
    const materialized = materializeArtifacts([sourceFileToArtifact(sourceFile)], root)
    const formatted = await formatMaterializedArtifacts(materialized.artifacts, 'biome')
    const content = decoder.decode(formatted.artifacts[0]?.content)

    expect(formatted.diagnostics).toEqual([])
    expect(content.startsWith(generatedTypeScriptHeader)).toBe(true)
    expect(content.match(/Generated by openapi-to\. DO NOT EDIT\./g)).toHaveLength(1)
    expect(formatted.artifacts[0]?.hash).toBe(hashArtifactContent(encoder.encode(content)))
  })

  it('deduplicates identical paths and rejects traversal, size, case, and content conflicts', () => {
    const root = path.resolve('/tmp/output')
    const result = materializeArtifacts([
      { kind: 'text', path: '../escape.txt', content: 'x' },
      { kind: 'text', path: path.resolve('/tmp/escape.txt'), content: 'x' },
      { kind: 'text', path: 'same.txt', content: 'a', plugin: 'a' },
      { kind: 'text', path: 'same.txt', content: 'a', plugin: 'a-copy' },
      { kind: 'text', path: 'same.txt', content: 'b', plugin: 'b' },
      { kind: 'text', path: 'Case.txt', content: 'c' },
      { kind: 'text', path: 'case.txt', content: 'c' },
      { kind: 'binary', path: 'large.bin', content: new Uint8Array([1, 2, 3, 4]) },
    ], root, { maxArtifactBytes: 3 })
    expect(result.artifacts.filter((artifact) => artifact.relativePath === 'same.txt')).toHaveLength(1)
    expect(result.diagnostics.map((diagnostic) => diagnostic.code)).toEqual(expect.arrayContaining([
      'ARTIFACT_PATH_OUTSIDE_OUTPUT',
      'ARTIFACT_PATH_CONFLICT',
      'ARTIFACT_PATH_CASE_CONFLICT',
      'ARTIFACT_TOO_LARGE',
    ]))
  })

  it('deletes only previously managed files when clean is enabled', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-clean-'))
    await writeFile(path.join(root, 'user.txt'), 'keep')
    const first = materializeArtifacts([{ kind: 'text', path: 'generated.txt', content: 'generated' }], root)
    const firstManifest = await compareArtifacts(first.artifacts, root, true)
    expect(firstManifest.entries.map((entry) => entry.path)).toEqual(['generated.txt'])
    await writeArtifacts(first.artifacts, firstManifest)

    const secondManifest = await compareArtifacts([], root, true)
    expect(secondManifest.entries).toEqual([
      expect.objectContaining({ path: 'generated.txt', status: 'deleted', previousHash: expect.stringMatching(/^[a-f0-9]{64}$/), bytes: 9 }),
    ])
    await writeArtifacts([], secondManifest)
    await expect(access(path.join(root, 'generated.txt'))).rejects.toThrow()
    await expect(access(path.join(root, ARTIFACT_MANIFEST_FILENAME))).rejects.toThrow()
    expect(await readFile(path.join(root, 'user.txt'), 'utf8')).toBe('keep')
  })

  it('rejects an existing unmanaged desired path without adopting or overwriting it', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-unmanaged-conflict-'))
    const existingPath = path.join(root, 'get-user.ts')
    await writeFile(existingPath, 'user-owned\n')
    const desired = materializeArtifacts([{ kind: 'text', path: 'get-user.ts', content: 'generated\n' }], root)

    await expect(compareArtifacts(desired.artifacts, root)).rejects.toMatchObject({
      code: 'OUTPUT_UNMANAGED_PATH_CONFLICT',
      relativePath: 'get-user.ts',
    })
    expect(await readFile(existingPath, 'utf8')).toBe('user-owned\n')
  })

  it('rejects byte-identical unmanaged paths and changed managed paths', async () => {
    const unmanagedRoot = await mkdtemp(path.join(os.tmpdir(), 'openapi-unmanaged-identical-'))
    await writeFile(path.join(unmanagedRoot, 'same.txt'), 'same\n')
    const unmanaged = materializeArtifacts([{ kind: 'text', path: 'same.txt', content: 'same\n' }], unmanagedRoot)
    await expect(compareArtifacts(unmanaged.artifacts, unmanagedRoot)).rejects.toMatchObject({
      code: 'OUTPUT_UNMANAGED_PATH_CONFLICT',
      relativePath: 'same.txt',
    })

    const managedRoot = await mkdtemp(path.join(os.tmpdir(), 'openapi-managed-drift-'))
    const initial = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'generated\n' }], managedRoot)
    await writeArtifacts(initial.artifacts, await compareArtifacts(initial.artifacts, managedRoot))
    await writeFile(path.join(managedRoot, 'owned.txt'), 'user change\n')
    const desired = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'next generated\n' }], managedRoot)
    await expect(compareArtifacts(desired.artifacts, managedRoot)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    const check = await compareArtifacts(desired.artifacts, managedRoot, false, { allowManagedDrift: true })
    expect(check).toMatchObject({ outdated: true, summary: { modified: 1 } })
    expect(check.entries).toEqual([expect.objectContaining({ path: 'owned.txt', status: 'modified', ownershipConflict: 'managed-changed' })])
    await expect(writeArtifacts(desired.artifacts, check)).rejects.toMatchObject({ code: 'OUTPUT_MANAGED_PATH_CHANGED', relativePath: 'owned.txt' })
    expect(await readFile(path.join(managedRoot, 'owned.txt'), 'utf8')).toBe('user change\n')
    await expect(compareArtifacts([], managedRoot, true)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    await writeFile(path.join(managedRoot, 'owned.txt'), 'next generated\n')
    await expect(compareArtifacts(desired.artifacts, managedRoot)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    expect(await readFile(path.join(managedRoot, 'owned.txt'), 'utf8')).toBe('next generated\n')
  })

  it('only upgrades legacy path-only ownership when the desired bytes are already identical', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-legacy-ownership-'))
    const ownedPath = path.join(root, 'owned.txt')
    const ownershipPath = path.join(root, ARTIFACT_MANIFEST_FILENAME)
    await writeFile(ownedPath, 'current bytes\n')
    await writeFile(ownershipPath, `${JSON.stringify({ version: 1, files: ['owned.txt'] }, null, 2)}\n`)

    const changed = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'new bytes\n' }], root)
    await expect(compareArtifacts(changed.artifacts, root)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    await expect(compareArtifacts([], root, true)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    const currentBytes = encoder.encode('current bytes\n')
    await writeFile(ownershipPath, `${JSON.stringify({
      version: 1,
      files: [{ path: 'owned.txt', sha256: hashArtifactContent(currentBytes), bytes: currentBytes.byteLength }],
    }, null, 2)}\n`)
    await expect(compareArtifacts(changed.artifacts, root)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    await expect(compareArtifacts([], root, true)).rejects.toMatchObject({
      code: 'OUTPUT_MANAGED_PATH_CHANGED',
      relativePath: 'owned.txt',
    })
    const lock = await acquireOutputWriteLock(root)
    try {
      const locked = await compareArtifacts(changed.artifacts, root, false, { outputWriteLock: lock })
      const withoutRetainedConflict = {
        ...locked,
        entries: locked.entries.map(({ ownershipConflict: _ownershipConflict, ...entry }) => entry),
      }
      await expect(writeArtifacts(changed.artifacts, withoutRetainedConflict, { lock })).rejects.toMatchObject({
        code: 'OUTPUT_MANAGED_PATH_CHANGED',
        relativePath: 'owned.txt',
      })
    } finally {
      await lock.release()
    }
    expect(await readFile(ownedPath, 'utf8')).toBe('current bytes\n')

    const identical = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'current bytes\n' }], root)
    const manifest = await compareArtifacts(identical.artifacts, root)
    expect(manifest.entries).toEqual([expect.objectContaining({ path: 'owned.txt', status: 'unchanged' })])
    await writeArtifacts(identical.artifacts, manifest, { generatorVersion: 'test' })
    expect(JSON.parse(await readFile(ownershipPath, 'utf8'))).toMatchObject({
      version: 2,
      files: [expect.objectContaining({ path: 'owned.txt', sha256: identical.artifacts[0]?.hash })],
    })
    expect(await readFile(ownedPath, 'utf8')).toBe('current bytes\n')
  })

  it('rejects an artifact omitted from the supplied manifest instead of adopting an unmanaged path', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-manifest-omission-'))
    await writeFile(path.join(root, 'same.txt'), 'same\n')
    const desired = materializeArtifacts([{ kind: 'text', path: 'same.txt', content: 'same\n' }], root)
    const lock = await acquireOutputWriteLock(root)
    try {
      await expect(writeArtifacts(desired.artifacts, {
        outputRoot: root,
        entries: [],
        summary: { added: 0, modified: 0, deleted: 0, unchanged: 0 },
        outdated: false,
      }, { lock })).rejects.toMatchObject({ name: 'OutputPreconditionChangedError', relativePath: 'same.txt' })
    } finally {
      await lock.release()
    }
    await expect(access(path.join(root, ARTIFACT_MANIFEST_FILENAME))).rejects.toThrow()
    expect(await readFile(path.join(root, 'same.txt'), 'utf8')).toBe('same\n')
  })

  it('retains ownership conflicts during locked revalidation and refuses to commit them', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-locked-conflict-'))
    await writeFile(path.join(root, 'conflict.txt'), 'user owned\n')
    const desired = materializeArtifacts([{ kind: 'text', path: 'conflict.txt', content: 'generated\n' }], root)
    const lock = await acquireOutputWriteLock(root)
    try {
      const manifest = await compareArtifacts(desired.artifacts, root, false, { outputWriteLock: lock })
      expect(manifest.entries).toEqual([
        expect.objectContaining({ path: 'conflict.txt', ownershipConflict: 'unmanaged' }),
      ])
      await expect(writeArtifacts(desired.artifacts, manifest, { lock })).rejects.toMatchObject({
        code: 'OUTPUT_UNMANAGED_PATH_CONFLICT',
        relativePath: 'conflict.txt',
      })
    } finally {
      await lock.release()
    }
    expect(await readFile(path.join(root, 'conflict.txt'), 'utf8')).toBe('user owned\n')
  })

  it('refuses a write when ownership is removed after comparison', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-ownership-race-'))
    const initial = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'before\n' }], root)
    await writeArtifacts(initial.artifacts, await compareArtifacts(initial.artifacts, root))
    const desired = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'after\n' }], root)
    const manifest = await compareArtifacts(desired.artifacts, root)
    await unlink(path.join(root, ARTIFACT_MANIFEST_FILENAME))

    await expect(writeArtifacts(desired.artifacts, manifest)).rejects.toMatchObject({
      code: 'OUTPUT_UNMANAGED_PATH_CONFLICT',
      relativePath: 'owned.txt',
    })
    expect(await readFile(path.join(root, 'owned.txt'), 'utf8')).toBe('before\n')
  })

  it('refuses to commit when an unchanged artifact drifts after staging', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-unchanged-race-'))
    const desired = materializeArtifacts([{ kind: 'text', path: 'owned.txt', content: 'generated\n' }], root)
    await writeArtifacts(desired.artifacts, await compareArtifacts(desired.artifacts, root))
    const manifest = await compareArtifacts(desired.artifacts, root)
    expect(manifest.entries[0]?.status).toBe('unchanged')

    await expect(writeArtifacts(desired.artifacts, manifest, {
      onPhase: async (phase) => {
        if (phase === 'staged') await writeFile(path.join(root, 'owned.txt'), 'external change\n')
      },
    })).rejects.toMatchObject({ name: 'OutputPreconditionChangedError', relativePath: 'owned.txt' })
    expect(await readFile(path.join(root, 'owned.txt'), 'utf8')).toBe('external change\n')
  })

  it('does not replace an unmanaged file that appears immediately before an added artifact is installed', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-added-install-race-'))
    const desired = materializeArtifacts([{ kind: 'text', path: 'late.txt', content: 'generated\n' }], root)
    const manifest = await compareArtifacts(desired.artifacts, root)

    await expect(writeArtifacts(desired.artifacts, manifest, {
      onPhase: async (phase) => {
        if (phase === 'committing') await writeFile(path.join(root, 'late.txt'), 'user late file\n')
      },
    })).rejects.toMatchObject({
      name: 'OutputTransactionRolledBackError',
      originalError: expect.objectContaining({ name: 'OutputPreconditionChangedError', relativePath: 'late.txt' }),
    })
    expect(await readFile(path.join(root, 'late.txt'), 'utf8')).toBe('user late file\n')
    await expect(access(path.join(root, ARTIFACT_MANIFEST_FILENAME))).rejects.toThrow()
  })

  it('does not create ownership state for an empty no-op write', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-empty-'))
    const manifest = await compareArtifacts([], root)
    await writeArtifacts([], manifest)
    await expect(access(path.join(root, ARTIFACT_MANIFEST_FILENAME))).rejects.toThrow()
  })

  it('rejects output-root and nested symlink escapes for writes and deletes', async () => {
    const parent = await mkdtemp(path.join(os.tmpdir(), 'openapi-symlink-'))
    const outside = path.join(parent, 'outside')
    const rootLink = path.join(parent, 'root-link')
    await mkdir(outside)
    await symlink(outside, rootLink, process.platform === 'win32' ? 'junction' : 'dir')
    const linkedRootArtifact = materializeArtifacts([{ kind: 'text', path: 'escape.txt', content: 'no' }], rootLink)
    await expect(compareArtifacts(linkedRootArtifact.artifacts, rootLink)).rejects.toThrow(/symlink/)

    const root = path.join(parent, 'root')
    await mkdir(root)
    await writeFile(path.join(outside, 'victim.txt'), 'keep')
    await symlink(outside, path.join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir')
    await writeFile(path.join(root, ARTIFACT_MANIFEST_FILENAME), `${JSON.stringify({
      version: 2,
      files: [{ path: 'linked/victim.txt', sha256: hashArtifactContent(encoder.encode('keep')), bytes: 4 }],
    })}\n`)
    const deletion = await compareArtifacts([], root, true)
    await expect(writeArtifacts([], deletion)).rejects.toThrow(/symlink/)
    expect(await readFile(path.join(outside, 'victim.txt'), 'utf8')).toBe('keep')
  })

  it('keeps the legacy SourceFile adapter deterministic', () => {
    const root = path.resolve('/tmp/source-adapter')
    const sourceFile = new Project({ useInMemoryFileSystem: true }).createSourceFile(path.join(root, 'legacy.ts'), 'export const x=1')
    const first = materializeArtifacts([sourceFileToArtifact(sourceFile)], root)
    const second = materializeArtifacts([sourceFileToArtifact(sourceFile)], root)
    expect(first.artifacts[0]?.hash).toBe(second.artifacts[0]?.hash)
  })

  it('fails closed when an existing generated file changes during comparison', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-compare-race-'))
    const file = path.join(root, 'large.txt')
    await writeFile(file, 'x'.repeat(8 * 1024 * 1024))
    const expected = materializeArtifacts([{ kind: 'text', path: 'large.txt', content: 'expected' }], root)
    const timer = setInterval(() => { void utimes(file, new Date(), new Date()) }, 1)
    await expect(compareArtifacts(expected.artifacts, root)).rejects.toMatchObject({ name: 'ArtifactComparisonChangedError' })
    clearInterval(timer)
  })

  it('fails closed when the ownership manifest changes during comparison', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'openapi-manifest-race-'))
    const manifestPath = path.join(root, ARTIFACT_MANIFEST_FILENAME)
    await writeFile(manifestPath, `${JSON.stringify({ version: 1, files: [], padding: 'x'.repeat(8 * 1024 * 1024) })}\n`)
    const timer = setInterval(() => { void utimes(manifestPath, new Date(), new Date()) }, 1)
    await expect(compareArtifacts([], root, true)).rejects.toMatchObject({ name: 'ArtifactComparisonChangedError' })
    clearInterval(timer)
  })
})
