export const INTAKE_SCHEMA_VERSION = 1;
export const INTAKE_POLICY_VERSION = '1.0.0-shadow';

export const INTAKE_STATUS = Object.freeze({
  ELIGIBLE: 'ELIGIBLE_FOR_AUTHORIZED_SPAWN',
  HUMAN: 'REQUIRE_HUMAN',
  BLOCKED: 'BLOCKED',
});

export const REASON = Object.freeze({
  INVALID_INPUT: 'INVALID_INPUT',
  SCHEMA_VERSION_UNSUPPORTED: 'SCHEMA_VERSION_UNSUPPORTED',
  POLICY_EXPIRED: 'POLICY_EXPIRED',
  POLICY_BINDING_MISMATCH: 'POLICY_BINDING_MISMATCH',
  POLICY_SHA_MISMATCH: 'POLICY_SHA_MISMATCH',
  REPOSITORY_MISMATCH: 'REPOSITORY_MISMATCH',
  ISSUE_ID_MISMATCH: 'ISSUE_ID_MISMATCH',
  ISSUE_NOT_OPEN: 'ISSUE_NOT_OPEN',
  RECEIPT_UNVERIFIED: 'RECEIPT_UNVERIFIED',
  RECEIPT_EXPIRED: 'RECEIPT_EXPIRED',
  RECEIPT_REVOKED: 'RECEIPT_REVOKED',
  RECEIPT_REPLAYED: 'RECEIPT_REPLAYED',
  ACTOR_UNVERIFIED: 'ACTOR_UNVERIFIED',
  CONTRACT_DIGEST_MISMATCH: 'CONTRACT_DIGEST_MISMATCH',
  MODE_NOT_AUTHORIZED: 'MODE_NOT_AUTHORIZED',
  HOST_CAPABILITY_UNVERIFIED: 'HOST_CAPABILITY_UNVERIFIED',
  NATIVE_BLOCKER_PRESENT: 'NATIVE_BLOCKER_PRESENT',
  DEPENDENCY_UNSATISFIED: 'DEPENDENCY_UNSATISFIED',
  WIP_LIMIT_REACHED: 'WIP_LIMIT_REACHED',
  DUPLICATE_EXECUTION_PRESENT: 'DUPLICATE_EXECUTION_PRESENT',
  MAIN_SHA_DRIFT: 'MAIN_SHA_DRIFT',
  HIGH_OR_UNKNOWN_RISK: 'HIGH_OR_UNKNOWN_RISK',
  WRITE_SURFACE_UNKNOWN: 'WRITE_SURFACE_UNKNOWN',
  PATH_PROOF_INVALID: 'PATH_PROOF_INVALID',
  HIGH_RISK_REQUIRES_HUMAN: 'HIGH_RISK_REQUIRES_HUMAN',
});

export const LIMITS = Object.freeze({
  titleBytes: 512,
  bodyBytes: 16_384,
  collectionItems: 100,
  pathBytes: 256,
});
