import process from 'node:process'
import { parseArgs } from 'node:util'

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'

import { version } from '../package.json'
import { createOpenapiToMcpServer } from './server.ts'
import { redirectIncidentalConsoleToStderr } from './logger.ts'
import type { GenerationMode } from './options.ts'
import { StartupConfigPreflightError, StartupPhaseError, writeStartupDiagnostic } from './startup-diagnostics.ts'

const HELP = `openapi-to-mcp — bounded OpenAPI MCP server

Usage:
  openapi-to-mcp [--workspace-root <path>] [--config <path>] [--generation-mode <mode>]

Options:
  --workspace-root <path>    Workspace boundary (default: current directory)
  --config <path>            Trusted project config fixed for the server lifetime
  --generation-mode <mode>   Generation capability: developer, read-only, or hardened (default: developer)
  --allow-host <hostname>    Allow a remote OpenAPI host (repeatable)
  --allow-private-network    Allow private-network sources; lowers the security boundary and is disabled by default
  --validate-timeout-ms <n>  Server timeout for validate in milliseconds (100..600000; default 30000)
  --inspect-timeout-ms <n>   Server timeout for inspect in milliseconds (100..600000; default 30000)
  --diff-timeout-ms <n>      Server timeout for diff in milliseconds (100..600000; default 45000)
  --generation-timeout-ms <n> Server timeout for dry-run/check in milliseconds (100..600000; default 60000)
  --plan-ttl-ms <n>          Controlled-write plan lifetime in milliseconds (1000..3600000; default 300000)
  --max-plans <n>            Maximum in-memory plans per Server (1..100; default 20)
  --max-plan-bytes <n>       Maximum metadata bytes per plan (65536..67108864; default 16777216)
  --max-total-plan-bytes <n> Maximum total plan metadata bytes (65536..536870912; default 67108864)
  --max-write-files <n>      Maximum managed files in one plan (1..50000; default 5000)
  --max-write-bytes <n>      Maximum generated bytes in one plan (1024..1073741824; default 268435456)
  --write-lock-wait-ms <n>   Maximum Apply wait for the cross-process output lock (100..600000; default 30000)
  --commit-timeout-ms <n>    Transaction commit/rollback deadline in milliseconds (100..600000; default 60000)
  --log-format <text|json>   Operational stderr log format (default: text)
  --log-level <level>        debug, info, warn, error, or silent (default: info)
  --help                     Show help
  --version                  Show version

The server uses stdio: stdin/stdout are reserved for MCP JSON-RPC and logs go to stderr.
`

interface CliValues {
  'workspace-root'?: string
  config?: string
  'generation-mode'?: string
  'allow-host'?: string[]
  'allow-private-network'?: boolean
  'validate-timeout-ms'?: string
  'inspect-timeout-ms'?: string
  'diff-timeout-ms'?: string
  'generation-timeout-ms'?: string
  'plan-ttl-ms'?: string
  'max-plans'?: string
  'max-plan-bytes'?: string
  'max-total-plan-bytes'?: string
  'max-write-files'?: string
  'max-write-bytes'?: string
  'write-lock-wait-ms'?: string
  'commit-timeout-ms'?: string
  'log-format'?: string
  'log-level'?: string
  help?: boolean
  version?: boolean
}

async function main(args: string[]): Promise<void> {
  let parsed: { values: CliValues }
  try {
    parsed = parseArgs({
      args,
      allowPositionals: false,
      options: {
        'workspace-root': { type: 'string' },
        config: { type: 'string' },
        'generation-mode': { type: 'string' },
        'allow-host': { type: 'string', multiple: true },
        'allow-private-network': { type: 'boolean', default: false },
        'validate-timeout-ms': { type: 'string' },
        'inspect-timeout-ms': { type: 'string' },
        'diff-timeout-ms': { type: 'string' },
        'generation-timeout-ms': { type: 'string' },
        'plan-ttl-ms': { type: 'string' },
        'max-plans': { type: 'string' },
        'max-plan-bytes': { type: 'string' },
        'max-total-plan-bytes': { type: 'string' },
        'max-write-files': { type: 'string' },
        'max-write-bytes': { type: 'string' },
        'write-lock-wait-ms': { type: 'string' },
        'commit-timeout-ms': { type: 'string' },
        'log-format': { type: 'string' },
        'log-level': { type: 'string' },
        help: { type: 'boolean', short: 'h', default: false },
        version: { type: 'boolean', short: 'v', default: false },
      },
    }) as { values: CliValues }
  } catch (error) {
    throw new StartupPhaseError('parse-arguments', error)
  }
  if (parsed.values.help) {
    process.stdout.write(HELP)
    return
  }
  if (parsed.values.version) {
    process.stdout.write(`${version}\n`)
    return
  }
  redirectIncidentalConsoleToStderr()
  try {
    const numberValue = (value: string | undefined) => (value === undefined ? undefined : Number(value))
    const logFormat = parsed.values['log-format']
    if (logFormat !== undefined && logFormat !== 'text' && logFormat !== 'json') throw new RangeError('--log-format must be text or json.')
    const logLevel = parsed.values['log-level']
    if (logLevel !== undefined && !['debug', 'info', 'warn', 'error', 'silent'].includes(logLevel)) throw new RangeError('--log-level must be debug, info, warn, error, or silent.')
    const generationModeValue = parsed.values['generation-mode'] ?? 'developer'
    if (!['developer', 'read-only', 'hardened'].includes(generationModeValue)) throw new RangeError('--generation-mode must be developer, read-only, or hardened.')
    const generationMode = generationModeValue as GenerationMode
    let server: ReturnType<typeof createOpenapiToMcpServer>
    try {
      server = createOpenapiToMcpServer({
        workspaceRoot: parsed.values['workspace-root'] ?? process.cwd(),
        ...(parsed.values.config ? { configPath: parsed.values.config } : {}),
        generationMode,
        remote: {
          allowPrivateNetwork: parsed.values['allow-private-network'],
          allowedHosts: parsed.values['allow-host'] ?? [],
        },
        timeouts: {
          validateMs: numberValue(parsed.values['validate-timeout-ms']),
          inspectMs: numberValue(parsed.values['inspect-timeout-ms']),
          diffMs: numberValue(parsed.values['diff-timeout-ms']),
          generationMs: numberValue(parsed.values['generation-timeout-ms']),
        },
        write: {
          planTtlMs: numberValue(parsed.values['plan-ttl-ms']),
          maxPlans: numberValue(parsed.values['max-plans']),
          maxPlanBytes: numberValue(parsed.values['max-plan-bytes']),
          maxTotalPlanBytes: numberValue(parsed.values['max-total-plan-bytes']),
          maxFiles: numberValue(parsed.values['max-write-files']),
          maxBytes: numberValue(parsed.values['max-write-bytes']),
          lockWaitMs: numberValue(parsed.values['write-lock-wait-ms']),
          commitTimeoutMs: numberValue(parsed.values['commit-timeout-ms']),
        },
        ...(logFormat ? { logFormat } : {}),
        ...(logLevel ? { logLevel: logLevel as 'debug' | 'info' | 'warn' | 'error' | 'silent' } : {}),
      })
    } catch (error) {
      throw new StartupPhaseError('resolve-server', error)
    }
    const transport = new StdioServerTransport()
    let closing = false
    const shutdown = async () => {
      if (closing) return
      closing = true
      await server.close()
    }
    process.stdin.once('end', () => { void shutdown() })
    process.once('SIGTERM', () => { void shutdown() })
    process.once('SIGINT', () => { void shutdown() })
    try {
      await server.connect(transport)
    } catch (error) {
      if (error instanceof StartupConfigPreflightError) throw new StartupPhaseError('config-preflight', error.cause)
      throw new StartupPhaseError('connect-transport', error)
    }
  } catch (error) {
    if (error instanceof StartupPhaseError) throw error
    throw new StartupPhaseError('resolve-server', error)
  }
}

export async function runMcpCli(args: string[]): Promise<void> {
  try {
    await main(args)
  } catch (error) {
    const failure = error instanceof StartupPhaseError ? error : new StartupPhaseError('resolve-server', error)
    const modeValue = args.includes('--generation-mode')
      ? args[args.indexOf('--generation-mode') + 1]
      : args.find((arg) => arg.startsWith('--generation-mode='))?.slice('--generation-mode='.length)
    const mode = modeValue === 'read-only' || modeValue === 'hardened' || modeValue === 'developer' ? modeValue : 'developer'
    const inlineLogFormat = args.find((arg) => arg.startsWith('--log-format='))?.slice('--log-format='.length)
    const logFormat = inlineLogFormat === 'json' || (args.includes('--log-format') && args[args.indexOf('--log-format') + 1] === 'json') ? 'json' : 'text'
    writeStartupDiagnostic(failure.cause, { phase: failure.phase, args, mode, logFormat })
    process.exitCode = 1
  }
}
